version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: tcs_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - '7000:7000'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  tcs_server:
    container_name: tcs_server
    ports:
      - 50051:50051
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    volumes:
      - /app/node_modules
    depends_on:
      - redis
volumes:
  redis_data:
    driver: local