version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_PASSWORD=password123
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local